### ISSUE TITLE
Multiplayer?

### ISSUE THREAD

**Issue by turbogizzmo** [TheAlienDrew/minecraft-classic#2]
Any way to re-enable the multiplayer function?

**Comment by TheAlienDrew** [comment]
Should be crafted the same as a Minecraft classic url... Except with the website link it's being hosted on + the URL parameters from the original invite link.

**Comment by turbogizzmo** [comment]
Mojang somehow removed or disabled the ability to have multiple users join the same world even though it still says you can invite users you just get a blank page. I wondered if there was a way to add it back if you host it yourself. 

https://mobile.twitter.com/mojangstatus/status/1126070107279695873

**Comment by TheAlienDrew** [comment]
That's a really old post. Also are you making sure that you're using Chrome?

**Comment by turbogizzmo** [comment]
When I was reading through the tweets it sounded like they never enabled it again but if it's working for you I will check my setting again. Thanks!

**Comment by TheAlienDrew** [comment]
> When I was reading through the tweets it sounded like they never enabled it again but if it's working for you I will check my setting again. Thanks!

@turbogizzmo I had time to check it out today, I guess it is not working. But I know I would not be able to re-enable it. There was parts of the classic website that pointed to some amazon servers that I couldn't extract resources from, likely being for the multiplayer server, at the time I cloned the website. But, since it's a complete recreation of minecraft classic, maybe https://github.com/MagnusMarx/MinecraftClassic.Net will be handy in getting your own personal server started, but it would require that you edit the online website classic version source to point to your classic multiplayer server

**Comment by turbogizzmo** [comment]
Thanks for checking. I did use wayback machine to see what they were doing but couldnt pull anything from the AWS /prod  server either.
